### ISSUE TITLE
无法获取表单信息

### ISSUE THREAD

**Issue by xdldm** [AntaresQAQ/campushoy-auto-sign#5]
环境：ubuntu v20.04
           nodejs v10.19.0

日志：yarn run v1.22.15
$ node -r tsconfig-paths/register dist/main.js | bunyan -L
[2021-10-31T19:31:35.075-07:00] DEBUG: Auto Sign/6305 on ubuntu: Loading School List...
[2021-10-31T19:31:35.201-07:00] DEBUG: Auto Sign/6305 on ubuntu: Successfully Get 2888 Schools
[2021-10-31T19:31:35.202-07:00]  INFO: Auto Sign/6305 on ubuntu: Initializing User 皖西学院
[2021-10-31T19:31:35.202-07:00] DEBUG: Auto Sign/6305 on ubuntu: Your School Id is "7ec615e0-5cba-4fe9-8d24-69f21790c079"
[2021-10-31T19:31:35.306-07:00] DEBUG: Auto Sign/6305 on ubuntu: Your School Name is 皖西学院 And Url is https://wxc.campusphere.net/iap
[2021-10-31T19:31:35.307-07:00]  INFO: Auto Sign/6305 on ubuntu: Loading Config for User 皖西学院
[2021-10-31T19:31:35.307-07:00] DEBUG: Auto Sign/6305 on ubuntu: Logging...
[2021-10-31T19:31:35.505-07:00] DEBUG: Auto Sign/6305 on ubuntu: Successfully Get lt=926be234229543398ea0a0c04f847d5b
[2021-10-31T19:31:35.958-07:00]  INFO: Auto Sign/6305 on ubuntu: User 皖西学院Logged Succeed
[2021-10-31T19:31:35.958-07:00] DEBUG: Auto Sign/6305 on ubuntu: Logging Finished
[2021-10-31T19:31:36.134-07:00] ERROR: Auto Sign/6305 on ubuntu: User 皖西学院initialization failed
[2021-10-31T19:31:36.134-07:00] ERROR: Auto Sign/6305 on ubuntu: Please Finish Task Config 皖西学院.yaml
    Error: Please Finish Task Config 皖西学院.yaml
        at User.loadTaskConfig (campushoy-auto-sign/dist/user/user.js:27:19)
        at async User.init (campushoy-auto-sign/dist/user/user.js:37:13)
        at async App.start (campushoy-auto-sign/dist/app.js:20:17)
        at async bootstrap (campushoy-auto-sign/dist/main.js:8:5)
Done in 1.60s.

 config.yaml：users: #用户列表
  - school: 皖西学院 # 用户1 学校名称
    username:  # 用户1 用户名，必须是一个字符串，如果是数字学号请使用''或""
    password:  # 用户1 密码，必须是一个字符串
    qq: # 用户2 推送QQ号，一个数字，

login:
  retryTimes: 5 # 登录重试次数
  captcha: # 自动打码
    enable: false # 必须是 true 或 false
    pdId:  # 请前往 http://www.fateadm.com 获取，选填
    pdKey: # 请前往 http://www.fateadm.com 获取，选填

noticer: # QQ消息推送
  enable: false # 必须是 true 或 false
  qq: # 负责推送消息的QQ号，一个数字，选填
  password: # 负责推送消息的QQ密码，一个字符串，选填

logLevel: debug # 日志级别 debug/info/warn/error

tasks下的<school_name>-<user_name>.yaml 只有 task: []内容

**Comment by xdldm** [comment]
我以为可以用来信息收集的，不好意思

**Comment by AntaresQAQ** [comment]
啊，你有信息收集吗？方便留一个联系方式吗？

**Comment by xdldm** [comment]
QQ 904125807，但我信息收集已经用别的项目弄好了
